apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-istio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/undostres321/argocd-bootstrap.git
    targetRevision: HEAD
    path: apps/argocd-istio
  destination:
    namespace: production
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true