apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-addons
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/undostres321/argocd-bootstrap.git
    targetRevision: HEAD
    path: apps/istio-addons
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true