apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: "production"
    istio-injection: "enabled"

---

apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-10"